# see https://github.com/staabm/annotate-pull-request-from-checkstyle
name: Anotate Checkstyle

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    check_fixtures:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none # disable xdebug, pcov
                    tools: cs2pr
            -   run: composer install --no-progress
            -   run: |
                    bin/rector p abz/DeadCode.php --set dead-code -n --autoload-file abz/DeadCode.php --output-format=checkstyle | cs2pr
